### ISSUE TITLE
Error: Can not initialize protocol module before app is ready

### ISSUE THREAD

**Issue by dbachko** [seanchas116/electron-safe-ipc#3]
Can not start the app, I am getting this error:

```
Uncaught Exception:
Error: Can not initialize protocol module before app is ready
    at Object.<anonymous> (~/.npm/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/protocol.js:8:11)
    at Object.<anonymous> (~/.npm/lib/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/protocol.js:109:4)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (~/dev/vclock/node_modules/electron-safe-ipc/protocol.js:10:18)
    at Module._compile (module.js:428:26)
```

**Comment by seanchas116** [comment]
You can avoid this error by requiring electron-safe-ipc after app is ready.

``` js
var app = require("app");
app.on("ready", function() {
  var ipc = require("electron-safe-ipc/main");
  ...
```

**Comment by dbachko** [comment]
Thank you

**Comment by dbachko** [comment]
Now I am getting this error:

```
Uncaught Exception:
TypeError: protocol.registerStringProtocol is not a function
    at Object.module.exports.register (~/app/node_modules/electron-safe-ipc/protocol.js:16:14)
    at Object.<anonymous> (~/app/node_modules/electron-safe-ipc/host.js:8:23)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at initMainWindow (~/app/index.js:68:15)
    at EventEmitter.<anonymous> (~/app/index.js:32:3)
```

**Comment by dbachko** [comment]
I found the problem, I have old version of electron package( the API was changed )
